[project]
name = "database-application-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "cryptography>=45.0.3",
    "pymysql>=1.1.1",
    "sqlalchemy>=2.0.41",
]
